pipeline {
    agent any

     stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/gauravkestwal/a-swiggy-clone.git'
            }
        }
        stage("Buildabd deploy docker image") {
        steps {
            script {
                // Build the Docker image
                sh 'docker build -t swegi13 .'
                sh 'docker run -d --name swegi13 -p 3000:3000 swegi13:latest'
            }
        }
     }
    }
}

